name: Go package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.16']
    env:
      SQLX_SQLITE_DSN: "./sqlxtest.db"
      SQLX_MYSQL_DSN: "root:example@localhost/sqlxtest?parseTime=true"
      SQLX_POSTGRES_DSN: "postgres://postgres:example@localhost/sqlxtest?sslmode=disable"
    services:
      mysql:
        image: mysql:5
        env:
          MYSQL_ROOT_PASSWORD: example
        ports:
          - 3306:3306
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: example
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
               
    steps:
      - uses: actions/checkout@v3
      - name: Local Services Workaround
        if: ${{ env.ACT }}
        run: |
          sudo apt-get update
          sudo apt-get -yqq install netcat-traditional
          make test_up
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: '${{ matrix.go-version }}'
      # - name: Build
      #   run: go build -v ./...
      - name: Test
        run: go test -v ./...
